
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "192.168.50.10"

  config.vm.synced_folder "../dev_box", "/vagrant", :owner => 'ubuntu', :group => 'www-data'
  config.vm.synced_folder "../html", "/var/www/html", :owner => 'ubuntu', :group => 'www-data'
  config.vm.synced_folder "../log", "/var/www/log", :owner => 'ubuntu', :group => 'www-data'

  config.vm.network :forwarded_port, guest: 9090, host: 9090, auto_correct: true, disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "./provision.sh", keep_color: true

end
